# Principle of Virtual Work
[//]: # latex new commands
\newcommand\orig[2]{\mathbf{r}_{#1}^{(#2)}}
\newcommand\bvec[2]{{\mathbf{e}_{#1}^{(#2)}}}
\newcommand\ddoubleunderline[1]{\underline{\underline{#1}}}

A constraint force essentially restricts the system's motion in certain directions. For example, a box on a floor does not sink into the floor because of contact force. A ball and socket joint exerts reaction forces in all three cartesian coordinates because it restricts translational motion. A frictionless pin exerts reactions forces in all three cartesian coordinates and two couple moments as it only allows rotation in one of its axis. 

When we attempt to develop equations of motion of complex rigid body systems, we often have to deal with "unknown" reaction or constraint forces often do not need to be computed in real world applications. In this section, we present how one can utilize principle of virtual work to develop equations of motion without having to consider the reaction forces. 

### Work Done by a Virtual Force